# Generated by Django 4.0.6 on 2022-12-15 04:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('embarazadas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalembarazada',
            name='des_edo_res',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='geo.entidad'),
        ),
        migrations.AddField(
            model_name='historicalembarazada',
            name='des_loc_res',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='geo.localidad'),
        ),
        migrations.AddField(
            model_name='historicalembarazada',
            name='des_mpo_res',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='+',
                                    to='geo.municipio'),
        ),
        migrations.AddField(
            model_name='historicalembarazada',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='embarazada',
            name='des_edo_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='geo.entidad'),
        ),
        migrations.AddField(
            model_name='embarazada',
            name='des_loc_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='geo.localidad'),
        ),
        migrations.AddField(
            model_name='embarazada',
            name='des_mpo_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='geo.municipio'),
        ),
    ]
