# Generated by Django 3.2.16 on 2023-02-18 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20230214_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='area',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidad',
            name='area',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manzana',
            name='area',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='area',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
