# Generated by Django 3.2.16 on 2023-02-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20230217_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidad',
            name='densidad',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localidad',
            name='densidad',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manzana',
            name='densidad',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='densidad',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
