# Generated by Django 4.0.6 on 2022-12-15 04:42

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fol_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ide_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('ide_ape_pat', models.CharField(blank=True, max_length=255, null=True)),
                ('ide_ape_mat', models.CharField(blank=True, max_length=255, null=True)),
                ('ide_sex',
                 models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Masculino'), (2, 'Femenino')], null=True)),
                ('num_ext', models.CharField(max_length=255)),
                ('num_int', models.CharField(blank=True, max_length=255, null=True)),
                ('ide_cal', models.CharField(max_length=255)),
                ('ide_fec_nac', models.DateField(blank=True, null=True)),
                ('ide_cp', models.CharField(max_length=5)),
                ('ide_col', models.CharField(blank=True, max_length=255, null=True)),
                ('cve_diag_final', models.PositiveSmallIntegerField(
                    choices=[(1, 'Dengue no grave'), (2, 'Dengue con signos de alarma'), (3, 'Dengue grave')],
                    null=True)),
                ('des_ocupacion', models.CharField(blank=True, max_length=255, null=True)),
                (
                    'geom',
                    django.contrib.gis.db.models.fields.PointField(blank=True, default=None, null=True, srid=4326)),
                ('fec_sol_aten', models.DateField(blank=True, null=True)),
                ('municipio',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.municipio')),
            ],
        ),
        migrations.CreateModel(
            name='DatosAgregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.PositiveSmallIntegerField(
                    choices=[(1, 'Número de casos'), (2, 'Temperatura mínima'), (3, 'Temperatura máxima'),
                             (4, 'Temperatura promedio'), (5, 'Precipitación')])),
                ('valor', models.FloatField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo.entidad')),
            ],
        ),
    ]
