# Generated by Django 4.0.5 on 2022-06-15 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('dengue', '0001_initial'),
        ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='des_edo_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.entidad'),
            ),
        migrations.AddField(
            model_name='vector',
            name='des_loc_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.localidad'),
            ),
        migrations.AddField(
            model_name='vector',
            name='des_mpo_res',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.municipio'),
            ),
        ]
