# Generated by Django 4.0.5 on 2022-06-15 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dengue', '0004_rename_loc_vector_geometry_and_more'),
        ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='fol_id',
            field=models.CharField(blank=True, max_length=255, null=True),
            ),
        ]
