# Generated by Django 4.0.5 on 2022-06-15 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dengue', '0007_remove_vector_creado'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='precision',
            ),
        ]
