# Generated by Django 4.0.5 on 2022-06-19 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0004_localidad_puntual'),
        ('dengue', '0008_remove_vector_precision'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='vector',
            name='localidad',
            ),
        migrations.AddField(
            model_name='vector',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.municipio'),
            ),
        ]
