# Generated by Django 3.2.13 on 2022-06-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0004_localidad_puntual'),
        ('dengue', '0009_remove_vector_localidad_vector_municipio'),
        ]

    operations = [
        migrations.CreateModel(
            name='DatosAgregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('casos', models.PositiveBigIntegerField()),
                ('precipitacion', models.PositiveBigIntegerField()),
                ('temperatura_maxima', models.PositiveBigIntegerField()),
                ('temperatura_minima', models.PositiveBigIntegerField()),
                ('temperatura_promedio', models.PositiveBigIntegerField()),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='geo.entidad')),
                ],
            ),
        ]
