# Generated by Django 4.0.6 on 2022-12-15 22:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entidad',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='localidad',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='manzana',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='geometry',
            new_name='geom',
        ),
    ]
