# Generated by Django 4.0.5 on 2022-06-15 03:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geo', 'install_extensions'),
        ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('cvegeo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nomgeo', models.CharField(max_length=80)),
                ('cve_ent', models.CharField(max_length=2)),
                ],
            options={
                'ordering': ['nomgeo'],
                },
            ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('cvegeo', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nomgeo', models.CharField(max_length=120)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_loc', models.CharField(max_length=4)),
                ('ambito',
                 models.PositiveSmallIntegerField(choices=[(0, 'No Aplica'), (1, 'Urbana'), (2, 'Rural')], null=True)),
                ('plano', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'Croquis')], null=True)),
                ],
            options={
                'ordering': ['nomgeo'],
                },
            ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('cvegeo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nomgeo', models.CharField(max_length=80)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('entidad',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.entidad')),
                ],
            options={
                'ordering': ['nomgeo'],
                },
            ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('cvegeo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('cve_ent', models.CharField(max_length=2)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_loc', models.CharField(max_length=4)),
                ('cve_ageb', models.CharField(max_length=4)),
                ('cve_mza', models.CharField(max_length=3)),
                ('ambito', models.PositiveSmallIntegerField(choices=[(0, 'No Aplica'), (1, 'Urbana'), (2, 'Rural')])),
                ('tipomza', models.PositiveSmallIntegerField(
                    choices=[(0, 'No Aplica'), (1, 'Típica'), (2, 'Atípica'), (3, 'Contenedora'), (4, 'Contenida'),
                             (5, 'Económica'), (6, 'Edificio-Manzana'), (7, 'Glorieta'), (8, 'Parque o Jardín'),
                             (9, 'Camellón'), (10, 'Bajo Puente')])),
                ('localidad',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.localidad')),
                ],
            ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.municipio'),
            ),
        migrations.CreateModel(
            name='Demograficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('object_id', models.PositiveIntegerField()),
                ('pobtot', models.PositiveIntegerField(blank=True, null=True, verbose_name='Población total')),
                ('pobmas', models.PositiveIntegerField(blank=True, null=True, verbose_name='Población masculina')),
                ('pobfem', models.PositiveIntegerField(blank=True, null=True, verbose_name='Población femenina')),
                ('content_type',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ],
            ),
        ]
