# Generated by Django 3.2.5 on 2021-10-29 07:22

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0002_auto_20211027_2144'),
        ]

    operations = [
        migrations.AlterField(
            model_name='ageb',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
            ),
        migrations.AlterField(
            model_name='entidad',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
            ),
        migrations.AlterField(
            model_name='localidad',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
            ),
        migrations.AlterField(
            model_name='manzana',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
            ),
        migrations.AlterField(
            model_name='municipio',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
            ),
        ]
