# Generated by Django 4.0.5 on 2022-06-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0002_alter_localidad_cvegeo'),
        ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='cvegeo',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
            ),
        ]
