# Generated by Django 4.0.5 on 2022-06-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0003_alter_localidad_cvegeo'),
        ]

    operations = [
        migrations.AddField(
            model_name='localidad',
            name='puntual',
            field=models.BooleanField(default=False),
            ),
        ]
