# Generated by Django 3.2.13 on 2022-07-13 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0004_localidad_puntual'),
        ]

    operations = [
        migrations.AlterField(
            model_name='demograficos',
            name='object_id',
            field=models.CharField(max_length=16),
            ),
        ]
