# Generated by Django 3.2.5 on 2021-10-30 08:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0005_auto_20211030_0139'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='ageb',
            ),
        ]
