# Generated by Django 3.2.5 on 2021-11-03 01:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0006_remove_localidad_ageb'),
        ]

    operations = [
        migrations.RemoveField(
            model_name='localidad',
            name='area',
            ),
        migrations.RemoveField(
            model_name='localidad',
            name='plano',
            ),
        migrations.CreateModel(
            name='LocalidadRural',
            fields=[
                ('cve_ent', models.CharField(max_length=2)),
                ('POBTOT', models.PositiveIntegerField(blank=True,
                                                       help_text='Total de personas que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de personas en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad.',
                                                       null=True, verbose_name='Población total')),
                ('POBMAS', models.PositiveIntegerField(blank=True,
                                                       help_text='Total de hombres que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de hombres en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad.',
                                                       null=True, verbose_name='Población masculina')),
                ('POBFEM', models.PositiveIntegerField(blank=True,
                                                       help_text='Total de mujeres que residen habitualmente en el país, entidad federativa, municipio y localidad. Incluye la estimación del número de mujeres en viviendas particulares sin información de ocupantes. Incluye a la población que no especificó su edad.',
                                                       null=True, verbose_name='Población femenina')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('cvegeo', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nomgeo', models.CharField(max_length=120)),
                ('cve_mun', models.CharField(max_length=3)),
                ('cve_loc', models.CharField(max_length=4)),
                ('cve_ageb', models.CharField(max_length=4, null=True)),
                ('plano', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'Croquis')], null=True)),
                ('ageb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.ageb')),
                ('entidad',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.entidad')),
                ('municipio',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.municipio')),
                ],
            options={
                'ordering': ['nomgeo'],
                },
            ),
        ]
