# Generated by Django 3.2.5 on 2021-11-03 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0007_auto_20211102_1953'),
        ]

    operations = [
        migrations.AddField(
            model_name='localidadrural',
            name='cve_mza',
            field=models.CharField(max_length=3, null=True),
            ),
        ]
