# Generated by Django 3.2.5 on 2021-11-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('geo', '0008_localidadrural_cve_mza'),
        ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='cvegeo',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
            ),
        migrations.AlterField(
            model_name='localidadrural',
            name='cvegeo',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
            ),
        ]
